sudo: false
language: C
services:
  - docker

cache:
  directories:
    - $HOME/.cache

env:
  global:
    - PRODUCT=tarantool-zmq
  matrix:
    # - OS=el DIST=6
    - OS=el DIST=7
    - OS=fedora DIST=27
    - OS=fedora DIST=28
    # - OS=ubuntu DIST=trusty
    - OS=ubuntu DIST=xenial
    - OS=ubuntu DIST=bionic
    # - OS=debian DIST=jessie
    - OS=debian DIST=stretch
    - OS=debian DIST=sid

matrix:
  allow_failures:
    - env: OS=el DIST=6
    - env: OS=el DIST=7
    - env: OS=fedora DIST=27
    - env: OS=fedora DIST=28
    - env: OS=ubuntu DIST=trusty
    - env: OS=ubuntu DIST=xenial
    - env: OS=ubuntu DIST=bionic
    - env: OS=debian DIST=jessie
    - env: OS=debian DIST=stretch
    - env: OS=debian DIST=sid

script:
  - git describe --long
  - git clone https://github.com/packpack/packpack.git packpack
  - packpack/packpack

before_deploy:
  - ls -l build/

deploy:
  # Deploy packages to PackageCloud
  # - provider: packagecloud
  #   username: tarantool
  #   repository: "1_8"
  #   token: ${PACKAGECLOUD_TOKEN}
  #   dist: ${OS}/${DIST}
  #   package_glob: build/*.{rpm,deb,dsc}
  #   skip_cleanup: true
  #   on:
  #     branch: master
  #     condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"

notifications:
  email:
    recipients:
      - bigbes@gmail.com
    on_success: change
    on_failure: always
